name: Test azurite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip isntall requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=azurite --cov-report=xml --cov-report=html