# This is a basic workflow to help you get started with Actions

name: Azurite CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        options: --blobHost 0.0.0.0
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=azurite --cov-report=xml --cov-report=html
